package usage

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// SQLSink is a Sink backed by any *sql.DB. The driver package supplies the DDL
// and INSERT statement so the schema is owned by the driver, not this file.
type SQLSink struct {
	db        *sql.DB
	insertSQL string
}

// NewSQLSink runs the schema DDL (idempotent CREATE TABLE / INDEX IF NOT
// EXISTS), then runs additive migrations so previously-deployed databases pick
// up new columns without a manual upgrade. On schema failure the supplied db
// is closed.
func NewSQLSink(db *sql.DB, ddl, insertSQL string) (*SQLSink, error) {
	if db == nil {
		return nil, fmt.Errorf("sql sink: db is nil")
	}
	if _, err := db.Exec(ddl); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("sql sink: init schema: %w", err)
	}
	if err := ensureColumns(db, DefaultTable, DefaultColumns(), DefaultColumnTypes); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("sql sink: migrate columns: %w", err)
	}
	return &SQLSink{db: db, insertSQL: insertSQL}, nil
}

// Record maps Event onto the INSERT column list. Column order matches DefaultColumns.
func (s *SQLSink) Record(ctx context.Context, e Event) error {
	_, err := s.db.ExecContext(ctx, s.insertSQL,
		e.EventID,
		e.RequestID,
		nullString(e.APIKeyID),
		nullString(e.TeamID),
		nullString(e.Endpoint),
		nullString(e.Alias),
		nullString(e.RequestedModel),
		nullString(e.ResolvedModel),
		nullString(e.Provider),
		nullString(e.UpstreamModel),
		nullString(e.ErrorType),
		nullString(e.StreamOutcome),
		e.StatusCode,
		boolInt(e.Success),
		boolInt(e.Streaming),
		e.AttemptCount,
		e.RetryCount,
		e.FailoverCount,
		e.InputTokens,
		e.OutputTokens,
		e.TotalTokens,
		e.CacheReadTokens,
		e.CacheCreationTokens,
		e.ReasoningTokens,
		e.InputCostMicros,
		e.OutputCostMicros,
		e.TotalCostMicros,
		e.DurationMS,
		e.TimeToFirstTokenMS,
		e.StartedAt.UTC(),
		e.CompletedAt.UTC(),
		nullString(e.ClientIP),
		nullString(e.UserAgent),
	)
	return err
}

// Close releases the underlying *sql.DB.
func (s *SQLSink) Close() error {
	if s.db == nil {
		return nil
	}
	return s.db.Close()
}

// DefaultInsertSQL builds the INSERT statement for the SQLSink column list.
// placeholders must match the target dialect ("?" for SQLite/MySQL, "$N" for Postgres).
func DefaultInsertSQL(table string, placeholders string) string {
	cols := DefaultColumns()
	ph := make([]string, len(cols))
	for i := range ph {
		ph[i] = placeholders
	}
	return fmt.Sprintf(
		"INSERT INTO %s (%s) VALUES (%s)",
		table,
		strings.Join(cols, ", "),
		strings.Join(ph, ", "),
	)
}

// DefaultColumns returns the canonical column list, in the order Record supplies values.
// New columns must be appended, never reordered, to keep insert value positions stable
// against existing INSERT statements generated by older binaries.
func DefaultColumns() []string {
	return []string{
		"event_id", "request_id", "api_key_id", "team_id",
		"endpoint", "alias", "requested_model", "resolved_model",
		"provider", "upstream_model", "error_type", "stream_outcome",
		"status", "success", "streaming", "attempts",
		"retries", "failovers", "input_tokens", "output_tokens",
		"total_tokens",
		"cache_read_tokens", "cache_creation_tokens", "reasoning_tokens",
		"input_cost_micros", "output_cost_micros", "total_cost_micros",
		"duration_ms", "ttft_ms", "started_at", "completed_at",
		"client_ip", "user_agent",
	}
}

// DefaultColumnTypes pairs each column from DefaultColumns with a SQL type
// declaration. It is used by the bundled SQLite driver to build the CREATE TABLE
// statement and by ensureColumns to backfill missing columns on existing DBs.
var DefaultColumnTypes = []string{
	"TEXT", "TEXT", "TEXT", "TEXT",
	"TEXT", "TEXT", "TEXT", "TEXT",
	"TEXT", "TEXT", "TEXT", "TEXT",
	"INTEGER", "INTEGER", "INTEGER", "INTEGER",
	"INTEGER", "INTEGER", "INTEGER", "INTEGER",
	"INTEGER",
	"INTEGER", "INTEGER", "INTEGER",
	"INTEGER", "INTEGER", "INTEGER",
	"INTEGER", "INTEGER", "TIMESTAMP", "TIMESTAMP",
	"TEXT", "TEXT",
}

// ensureColumns adds any columns from cols that are missing from table.
// It is a no-op when the table already has every column. This lets deployed
// SQLite databases created before a gateway upgrade pick up new fields without
// a destructive recreate.
func ensureColumns(db *sql.DB, table string, cols []string, types []string) error {
	if len(cols) != len(types) {
		return fmt.Errorf("columns/types length mismatch: %d vs %d", len(cols), len(types))
	}
	existing, err := tableColumns(db, table)
	if err != nil {
		return err
	}
	for i, name := range cols {
		if _, ok := existing[name]; ok {
			continue
		}
		stmt := fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", table, name, types[i])
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("add column %s: %w", name, err)
		}
	}
	return nil
}

// tableColumns returns the set of column names present in table. Works on any
// SQL dialect that implements the information_schema or pragma_table_info pragma.
func tableColumns(db *sql.DB, table string) (map[string]struct{}, error) {
	out := map[string]struct{}{}
	// Try SQLite pragma first (most common bundled driver).
	rows, err := db.Query(fmt.Sprintf("PRAGMA table_info(%s)", table))
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var cid int
			var name, ctype string
			var notnull, pk int
			var dflt sql.NullString
			if err := rows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err != nil {
				return nil, fmt.Errorf("scan pragma row: %w", err)
			}
			out[name] = struct{}{}
		}
		if err := rows.Err(); err != nil {
			return nil, err
		}
		if len(out) > 0 {
			return out, nil
		}
	}
	// Fall back to information_schema (Postgres / MySQL).
	rows, err = db.Query(
		"SELECT column_name FROM information_schema.columns WHERE table_name = ? OR table_name = $1",
		table,
	)
	if err != nil {
		// Some drivers (sqlite) don't bind positional placeholders for $1; retry with ?.
		rows, err = db.Query(
			"SELECT column_name FROM information_schema.columns WHERE table_name = ?",
			table,
		)
		if err != nil {
			return nil, fmt.Errorf("read columns: %w", err)
		}
	}
	defer rows.Close()
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		out[name] = struct{}{}
	}
	return out, rows.Err()
}

// DefaultTable is the table name used by the bundled SQLite driver.
const DefaultTable = "usage_events"

func nullString(v string) sql.NullString {
	if v == "" {
		return sql.NullString{}
	}
	return sql.NullString{String: v, Valid: true}
}

func boolInt(b bool) int {
	if b {
		return 1
	}
	return 0
}
